version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ./mongodata:/data/db
        networks:
            - db-networks

networks:
  db-networks:
    driver: bridge
